<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>XPAB</AssemblyName>

    <ModLoader Condition="'$(ModLoader)' == ''">None</ModLoader>

    <DefineConstants Condition="'$(ModLoader)' == 'BepInEx'">$(DefineConstants);BEPINEX</DefineConstants>
    <DefineConstants Condition="'$(ModLoader)' == 'MelonLoader'">$(DefineConstants);MELON_LOADER</DefineConstants>
    <DefineConstants Condition="'$(ModLoader)' == 'Custom'">$(DefineConstants);CUSTOM_LOADER</DefineConstants>

    <CompileTarget Condition="'$(CompileTarget)' == ''">Mono</CompileTarget>

    <DefineConstants Condition="'$(CompileTarget)' == 'Mono'">$(DefineConstants);MONO</DefineConstants>
    <DefineConstants Condition="'$(CompileTarget)' == 'Il2Cpp'">$(DefineConstants);IL2CPP</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../Core/**/*.cs" />

    <Reference Condition="'$(CompileTarget)' == 'Mono'" Include="../UnityMono/*.dll" Private="false" />
    <Reference Condition="'$(CompileTarget)' == 'Il2Cpp'" Include="../UnityIl2Cpp/*.dll" Private="false" />

    <Reference Condition="'$(ModLoader)' == 'BepInEx'" Include="../BepInEx/*.dll" Private="false" />
    <Reference Condition="'$(ModLoader)' == 'MelonLoader'" Include="../MelonLoader/*.dll" Private="false" />
    <Reference Condition="'$(ModLoader)' == 'Custom'" Include="../CustomLoader/*.dll" Private="false" />
  </ItemGroup>
</Project>
