<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>XPAB.Runtime</AssemblyName>

    <ModLoader Condition="'$(ModLoader)' == ''">None</ModLoader>

    <DefineConstants Condition="'$(ModLoader)' != 'None'">$(DefineConstants);USES_LOADER</DefineConstants>
    <DefineConstants Condition="'$(ModLoader)' == 'BepInEx'">$(DefineConstants);BEPINEX</DefineConstants>
    <DefineConstants Condition="'$(ModLoader)' == 'MelonLoader'">$(DefineConstants);MELON_LOADER</DefineConstants>
    <DefineConstants Condition="'$(ModLoader)' == 'Custom'">$(DefineConstants);CUSTOM_LOADER</DefineConstants>

    <CompileTarget Condition="'$(CompileTarget)' == ''">Mono</CompileTarget>

    <DefineConstants Condition="'$(CompileTarget)' == 'Mono'">$(DefineConstants);MONO</DefineConstants>
    <DefineConstants Condition="'$(CompileTarget)' == 'Il2Cpp'">$(DefineConstants);IL2CPP</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../Core/**/*.cs" />

    <Reference Include="../Game/*.dll" Private="false" />

    <Reference Condition="'$(CompileTarget)' == 'Mono'" Include="../UnityMono/*.dll" Private="false" />
    <Reference Condition="'$(CompileTarget)' == 'Il2Cpp'" Include="../UnityIl2Cpp/*.dll" Private="false" />

    <Reference Condition="'$(ModLoader)' == 'BepInEx'" Include="../BepInEx/*.dll" Private="false" />
    <Reference Condition="'$(ModLoader)' == 'MelonLoader'" Include="../MelonLoader/*.dll" Private="false" />
    <Reference Condition="'$(ModLoader)' == 'Custom'" Include="../CustomLoader/*.dll" Private="false" />

    <Reference Condition="'$(ModLoader)' == 'BepInEx' and '$(CompileTarget)' == 'Il2Cpp'" Include="../BepIl2Cpp/*.dll" Private="false" />
    <Reference Condition="'$(ModLoader)' == 'MelonLoader' and '$(CompileTarget)' == 'Il2Cpp'" Include="../MelonIl2Cpp/*.dll" Private="false" />
    <Reference Condition="'$(ModLoader)' == 'Custom' and '$(CompileTarget)' == 'Il2Cpp'" Include="../CustomIl2Cpp/*.dll" Private="false" />

    <Reference Condition="'$(ModLoader)' == 'BepInEx' and '$(CompileTarget)' == 'Mono'" Include="../BepMono/*.dll" Private="false" />
    <Reference Condition="'$(ModLoader)' == 'MelonLoader' and '$(CompileTarget)' == 'Mono'" Include="../MelonMono/*.dll" Private="false" />
    <Reference Condition="'$(ModLoader)' == 'Custom' and '$(CompileTarget)' == 'Mono'" Include="../CustomMono/*.dll" Private="false" />

    <PackageReference Include="NVorbis" Version="1.0.0-rc.2" />
  </ItemGroup>

  <Target Name="ILRepack" AfterTargets="Build">
    <ItemGroup>
      <InputAssemblies Include="$(OutputPath)$(AssemblyName).dll" />
      <InputAssemblies Include="$(OutputPath)NVorbis.dll" />
    </ItemGroup>

    <ILRepack
      OutputType="Dll"
      Internalize="true"
      MainAssembly="$(OutputPath)$(AssemblyName).dll"
      OutputAssembly="$(OutputPath)$(AssemblyName).dll"
      InputAssemblies="@(InputAssemblies)"
      LibraryPath="$(OutputPath)" />
  </Target>
</Project>
