<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>XPAB.Editor</AssemblyName>
    <DefineConstants>$(DefineConstants);UNITY_EDITOR</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../Core/**/*.cs" />

    <Reference Include="../UnityMono/*.dll" Private="false" />
    <Reference Include="../UnityEditor/*.dll" Private="false" />
  </ItemGroup>
</Project>
